---
version: "2.1"
services:
#
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${LOCVOL1}heimdall:/config
    #ports:
      #- 52080:80
      #- 52443:443
    restart: unless-stopped
#
#
networks:
  default:
    external:
      name: ${CONNET}
