---
version: "2.1"
services:
  adminer:
    image: lscr.io/linuxserver/nginx:latest
    container_name: adminer
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      #- DOCKER_MODS=linuxserver/mods:swag-imagemagick|linuxserver/mods:universal-cron
    volumes:
      - ${LOCVOL1}adminer:/config
    ports:
      - 10082:80
    restart: unless-stopped
#
#
#
networks:
  default:
    external: true
    name: ${CONNET}